### ISSUE TITLE
feat(loading-icon): integrate loading icons with photo and gallery components

### ISSUE THREAD

**Issue by JayKan** [JayKan/angular2-instagram#15]
@damnko,

Upon selecting a new image from Unsplash action, there should be a loading icon indicator on both photo and gallery components ideally:

- [ ] A loading icon for photo component
- [ ] Each preset image should also render a loading icon

Let me know what you think!

**Comment by damnko** [comment]
Hi @JayKan I'm unsure on how to achieve this.

It seems like the only moment where the app actually sends a request to the unsplash api and wait for a response is during the initial fetch. When a new image is selected from the gallery only the image `src` gets updated but how do I know when the image has been completely loaded (to show/hide the loading indicator)?

Regardless of the point above, do you think the best approach would be to update the store to reflect the loading state of the app or would you rather keep that state in a service or pass that value directly to the interested components?

Thanks

**Comment by JayKan** [comment]
@damnko,

Yes you should another another property on the filtersState to keep track the loading-icon status upon selecting a new image. Since we're using the Redux/Store pattern, you wanna keep all data in the Store instead of having them in services.

**Comment by damnko** [comment]
Ok thanks and what about the first part of the question?

**Comment by JayKan** [comment]
@damnko,

You can use `ngIf` directive on the loading cmp, and sets the `ngIf === selectedImageSrc`. While on reselecting on a new image, you can use timeout() function to emulate 1 second delay to show loading. Let me know what you think.

**Comment by damnko** [comment]
Ok but isn't that just simulating a loading? What do you think if we just show the loading after the image gets selected and hide it once the Observable resolves? 
It will probably last less than 1 sec. Please share your thoughts! Thanks

**Comment by JayKan** [comment]
@damnko,

That also sounds like a reasonable approach, you can definitely give a try on that!
