### ISSUE TITLE
feat(core): update filters value accordingly upon selecting a preset image

### ISSUE THREAD

**Issue by JayKan** [JayKan/angular2-instagram#2]
Currently, when users select a preset image, the filters values are stay put, instead the filters values should be updated accordingly to the precomputed preset image, thus makes a smoother user interaction overall.

**Comment by damnko** [comment]
Hi Jay, so the way I would do it would be by passing along the `key` of the clicked image from `gallery.ts` down to `filters-reducer.ts` and then on the `FiltersActions.CHANGE_PRESET` case I would update the filters with something like
```
const chosenPreset = presets[key];
filtersState
    .merge({ 'contrast'  : chosenPreset.filter.get('contrast')  || 0 })
    .merge({ 'grayScale' : chosenPreset.filter.get('grayscale') || 0 })
    // ...
```
I am pretty sure that's not the best way of doing it so please feel free to share with me any suggestion or feedback.
Thanks

**Comment by JayKan** [comment]
@damnko,

Looks good to me. Do you have a working branch where I can take a look at? We can discuss the refactoring part later once you have a working prototype.

**Comment by damnko** [comment]
I haven't actually worked on it yet since I wanted to get a feedback from you first. Hopefully I will create a PR tomorrow so you can have a look at it.
Hope this sounds good to you.

**Comment by JayKan** [comment]
@damnko,

Sounds good to me. Make sure the production build is running after your changes :)
