### ISSUE TITLE
docs: add DOCUMENTATION for downloading `electron:package` app

### ISSUE THREAD

**Issue by JayKan** [JayKan/angular2-instagram#28]
@damnko,

After running `electron:package`,  a `dist` version has been produced. How do other people download the desktop app? Do you happen to know? Also, does the current `dist` version supports `Mac`, `Windows` and `Linux` or only `Mac`? If so, is there any way we can generate the `Windows` and `Linux` versions as well?

I think it's good to write up a separate documentation for this. Let me know what you think!

**Comment by damnko** [comment]
Hi @JayKan I'm just passing by, I will get back to you tomorrow.
I'm currently on Linux and it's working fine here, I had problems with the Windows version because I had to install `Wine` and I didn't manage to make it work. It would be probably easier to build it directly from Windows rather than from Linux/Mac. Anyway, I think I should give it another try with `electron-builder` that maybe gives better support for native app installers since the actual output in the `/dist` folder is just a (pretty big) executable.

Also, what do you mean by
> How do other people download the desktop app?

You would like to make the desktop app downloadable directly from the repo?

I'd say to fix the various problems and the process to create the desktop app and then we'll refactor the documentation accordingly.
Thanks for your feedback and suggestions!

**Comment by JayKan** [comment]
`How do other people download the desktop app?`

Yes, I would like to have other ppl to download directly from somewhere either as a Mac or Windows app. The idea is to have other people to install/download our `package` version somewhere, either from our repo or some other platforms, where they can directly download and play around on their own devices.

**Comment by damnko** [comment]
This is indeed a nice feature. At the moment I have no ideas on how to achieve it by the way.
I will look into it, if you have any suggestion feel free to share it!

**Comment by damnko** [comment]
I feel this is somehow related to #29

I did some testing with `electron-builder` and I think we can move forward in that direction. This is what we'll need atm:
* a `background.png`  used as macOS DMG background
* app icons in the form of `icon.icns` (macOS app icon) and `icon.ico` (Windows app icon)
* the same icons in `.png` format named `24x24.png`, `32x32.png`, `48x48.png`, `64x64.png`, `128x128.png`, `256x256.png` each with the corresponding dimensions

I also had a look at how to publish the executable app and `electron-builder` makes that pretty easy, we just need to decide what's the best workflow in our case. The only thing needed is to change the `version` in `package.json` and then run `node_modules/.bin/build -l -p always` (for Linux) and it will create a `release` in the repo and upload the executables. In order for this to work you will first need to create a github token with repo access via https://github.com/settings/tokens/new and then locally set the env variable with eg. `export GH_TOKEN="<TOKEN_HERE>"`.

I wanted to know what you think and if you feel it is right to manually create a release and not delegating this to the CI pipeline.

**Comment by JayKan** [comment]
@damnko,

Can we consolidate all the electron related sources/steps in a different documentation? That way it's a lot easier to get the full picture in the long run. In the doc, we can have a list to dos so we can track what we need to implement or not.

**Comment by damnko** [comment]
You mean to create sort of another readme file with info related to Electron? Eg. if we migrate to `electron-builder` would you keep also references to `electron-package`?

**Comment by JayKan** [comment]
@damnko,

Yes create another REAMDE to document all `electron` related stuffs, and I would like to keep both `electron-builder` and `electron-package`.

**Comment by JayKan** [comment]
@damnko,

Is there anyway you can create those Icons? I have no preference how icons should look like, but anything could work. I can always go back to get a better ions later on

**Comment by damnko** [comment]
Sure, I will update the PR later with the icons

**Comment by JayKan** [comment]
Thanks a lot @damnko 👍
