### ISSUE TITLE
Open any photo and save it

### ISSUE THREAD

**Issue by Suleman-Elahi** [JayKan/angular2-instagram#46]
Hi, it is actually a feature request.

If the desktop app can have an option to import a photo and export it back after applying filters in an easy way, then that would be nice :D

**Comment by JayKan** [comment]
Hi @Suleman-Elahi,

That would be an awesome idea only except the current way I'm modifying the images filters effects is via CSS filtering. But if you have any ideas/suggestions on how to make this happen, let's have a further conversations on this 👍
